# Generated by Django 5.0 on 2024-03-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sitefixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitefixed',
            name='global_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='global ID'),
        ),
    ]
