# Generated by Django 5.0 on 2024-03-14 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_sitefixed_global_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyFuel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Tasks', models.CharField(choices=[('Diesel Filling and Energy Reading', 'Diesel Filling and Energy Reading'), ('Energy Reading', 'Energy Reading')], max_length=200, verbose_name='Tasks')),
                ('DG_Serial_Number', models.TextField(null=True, verbose_name='DG Serial Number')),
                ('DG_HMR_Status', models.CharField(choices=[('Available', 'Available'), ('Not-Available', 'Not-Available')], max_length=30, null=True, verbose_name='DG HMR Status')),
                ('DG_HMR_Reading', models.IntegerField(null=True, verbose_name='DG HMR Reading')),
                ('DG_PIU_Status', models.CharField(choices=[('Available', 'Available'), ('Not-Available', 'Not-Available')], max_length=30, null=True, verbose_name='DG PIU Status')),
                ('Current_DG_PIU_Reading', models.IntegerField(null=True, verbose_name='Current DG PIU Reading')),
                ('Diesel_Filling_Done', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True, verbose_name='Diesel Filling Done')),
                ('Date_Of_Diesel_Filling', models.DateField(null=True, verbose_name='Date of Diesel Filling')),
                ('Diesel_Balance_Before_Filling', models.IntegerField(null=True, verbose_name='Diesel Balance Before Filling')),
                ('Fuel_Qty_Filled', models.IntegerField(null=True, verbose_name='Fuel Qty. Filled')),
                ('Current_Diesel_Balance', models.IntegerField(null=True, verbose_name='Current Diesel Balance')),
                ('EB_Meter_Status', models.CharField(choices=[('Available', 'Available'), ('Not-Available', 'Not-Available')], max_length=30, null=True, verbose_name='EB Meter Status')),
                ('Current_EB_MTR_KWH', models.IntegerField(null=True, verbose_name='Current EB MTR (KWH)')),
                ('EB_PIU_Meter_Status', models.CharField(choices=[('Available', 'Available'), ('Not-Available', 'Not-Available')], max_length=30, null=True, verbose_name='EB PIU Meter Status')),
                ('Current_EB_PIU_Reading', models.IntegerField(null=True, verbose_name='Current EB PIU Reading')),
                ('Total_DC_Load', models.IntegerField(null=True, verbose_name='Total DC Load')),
                ('Total_EB_KWH_Reading_from_all_Channels', models.IntegerField(null=True, verbose_name='Total EB KWH Reading from all channels')),
                ('Remarks', models.TextField(null=True, verbose_name='Remarks')),
                ('FT_ID', models.CharField(max_length=50, null=True, verbose_name='FT ID')),
                ('FT_name', models.CharField(max_length=200, null=True, verbose_name='FT Name')),
                ('FT_mobile_no', models.CharField(max_length=10, verbose_name='FT Mobile No')),
                ('Receipt_No', models.CharField(max_length=200, null=True, verbose_name='Receipt Number')),
                ('Card_Number', models.CharField(max_length=200, null=True, verbose_name='Card Number')),
                ('Vehicle_Plate', models.CharField(max_length=200, null=True, verbose_name='Vehicle Plate')),
                ('EB_Cumulative_KWH_Image', models.ImageField(null=True, upload_to='EB Cumulative KWH (As Per EB Meter)/%y', verbose_name='EB Cumulative KWH (As Per EB Meter) Image')),
                ('EB_Running_Hours_Cumulative_Image', models.ImageField(null=True, upload_to='EB Cumulative KWH (As Per EB Meter)/%y', verbose_name='EB Cumulative KWH (As Per EB Meter) Image')),
                ('DG_Running_Hours_Reading_Image', models.ImageField(null=True, upload_to='DG Running Hours Reading (As Per HMR Meter)/%y', verbose_name='DG Running Hours Reading (As Per HMR Meter) Image')),
                ('DG_Running_Hours_as_per_piu_Reading_Image', models.ImageField(null=True, upload_to='DG Running Hours Reading (As Per PIU/12PMS/AMF)/%y', verbose_name='DG Running Hours Reading (As Per PIU/12PMS/AMF) Image')),
                ('Diesel_Bill_Number_Image', models.ImageField(null=True, upload_to='Diesel Bill Number/%y', verbose_name='Diesel Bill Number Image')),
                ('DG_Running_HRS', models.TextField(null=True, verbose_name='DG Running Hrs')),
                ('CPH_CPH_Comparison_With_Last_CPH', models.TextField(null=True, verbose_name='CPH and CPH Comparioson with Approved')),
                ('CPH_as_par_HMR', models.TextField(null=True, verbose_name='CPH')),
                ('CPH_as_par_PIU', models.TextField(null=True, verbose_name='CPH')),
                ('EB_KWH', models.TextField(null=True, verbose_name='EB KWH')),
                ('global_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sitefixed')),
            ],
        ),
    ]
