# Generated by Django 5.0 on 2024-03-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_energyfuel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelDrawn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FT_ID', models.CharField(max_length=50, verbose_name='FT ID')),
                ('FT_name', models.CharField(max_length=200, verbose_name='FT Name')),
                ('FT_mobile_no', models.CharField(max_length=10, verbose_name='FT Mobile No')),
                ('Cluster_Name', models.CharField(choices=[('Balasore', 'Balasore'), ('Baripada', 'Baripada'), ('Berhampur', 'Berhampur'), ('Bhadrak', 'Bhadrak'), ('Bhubaneswar', 'Bhubaneswar'), ('Cuttack', 'Cuttack'), ('Paradeep', 'Paradeep'), ('Puri', 'Puri'), ('Rouekela', 'Rouekela'), ('Sambalpur', 'Sambalpur')], max_length=50, verbose_name='Cluster Name')),
                ('Fuel_Drawn_Date', models.DateField(verbose_name='Fuel Drawn Date')),
                ('Card_No', models.TextField(verbose_name='Booklet No. / Card No.')),
                ('City_Township_Fuel_Station', models.TextField(verbose_name='City /Township (Fuel Station)')),
                ('Customer', models.CharField(choices=[('ATC', 'ATC'), ('JIO', 'JIO')], max_length=20, verbose_name='Customer')),
                ('Fuel_Station_Name', models.TextField(verbose_name='Fuel Station Name')),
                ('Diesel_Purchased_Qty', models.IntegerField(verbose_name='Diesel Purchased Qty. (Liters)')),
                ('Diesel_Per_Ltr_Cost_Rs', models.IntegerField(verbose_name='Diesel Per Ltr. Cost. Rs.')),
                ('Total_Diesel_Cost_Rs', models.IntegerField(verbose_name='Total Diesel Cost Rs.')),
                ('Receipt_No', models.TextField(verbose_name='Receipt No')),
                ('Receipt_Image_Upload', models.ImageField(upload_to='Receipt Image Upload/%y', verbose_name='Receipt Image Upload')),
                ('Vehicle_Plate', models.TextField(verbose_name='Vehicle Plate')),
                ('Remarks', models.TextField(verbose_name='Remarks')),
            ],
        ),
    ]
