# Generated by Django 5.0 on 2024-03-17 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_fueldrawn'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyDieelFilling',
            fields=[
                ('file', models.FileField(null=True, upload_to='Diesel_Filling_PDF_Files/%y', verbose_name='File')),
                ('File_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='File ID')),
                ('Circle', models.TextField(null=True, verbose_name='Circle')),
                ('Site_Name', models.TextField(null=True, verbose_name='Site Name')),
                ('Cluster', models.TextField(null=True, verbose_name='Cluster')),
                ('Region', models.TextField(null=True, verbose_name='Region')),
                ('User_Name', models.TextField(null=True, verbose_name='User Name')),
                ('Assign_Date', models.DateField(null=True, verbose_name='Assign Date')),
                ('Status', models.TextField(null=True, verbose_name='Status')),
                ('Previous_Reading_Date_Time', models.DateTimeField(null=True, verbose_name='Previous Reading Date Time')),
                ('Current_Reading_Date_Time', models.DateTimeField(null=True, verbose_name='Current Reading Date Time')),
                ('Previous_EB_Cumulative_KWH_As_Per_EB_Meter', models.TextField(null=True, verbose_name='Previous EB Cumulative KWH As Per EB Meter')),
                ('Current_EB_Cumulative_KWH_As_Per_EB_Meter', models.TextField(null=True, verbose_name='Current EB Cumulative KWH As Per EB Meter')),
                ('Previous_EB_Running_Hours_Cumulative_Available_Not_Available', models.CharField(choices=[('Available', 'Available'), ('Not-Available', 'Not-Available')], max_length=20, null=True, verbose_name='Previous EB Running Hours Cumulative Available Not Available')),
                ('Current_EB_Running_Hours_Cumulative_Available_Not_Available', models.CharField(choices=[('Available', 'Available'), ('Not-Available', 'Not-Available')], max_length=20, null=True, verbose_name='Current EB Running Hours Cumulative Available Not Available')),
                ('Previous_EB_Running_Hours_Cumulative_As_per_PIU_I2PMS_AMF', models.TextField(null=True, verbose_name='Previous EB Running Hours Cumulative As per PIU I2PMS AMF')),
                ('Current_EB_Running_Hours_Cumulative_As_per_PIU_I2PMS_AMF', models.TextField(null=True, verbose_name='Current EB Running Hours Cumulative As per PIU I2PMS AMF')),
                ('Previous_Type_of_DG_Static_Mobile', models.CharField(choices=[('Static', 'Static'), ('Mobile', 'Mobile')], max_length=20, null=True, verbose_name='Previous Type of DG Static Mobile')),
                ('Current_Type_of_DG_Static_Mobile', models.CharField(choices=[('Static', 'Static'), ('Mobile', 'Mobile')], max_length=20, null=True, verbose_name='Current Type of DG Static Mobile')),
                ('Previous_DG_Running_Hours_Reading_As_Per_HMR', models.TextField(null=True, verbose_name='Previous DG Running Hours Reading (As Per HMR)')),
                ('Current_DG_Running_Hours_Reading_As_Per_HMR', models.TextField(null=True, verbose_name='Current DG Running Hours Reading (As Per HMR)')),
                ('Previous_DG_Running_Hours_Reading_As_Per_PIU_I2PMS_AMF', models.TextField(null=True, verbose_name='Previous DG Running Hours Reading(As Per PIU/I2PMS/AMF)')),
                ('Current_DG_Running_Hours_Reading_As_Per_PIU_I2PMS_AMF', models.TextField(null=True, verbose_name='Current DG Running Hours Reading(As Per PIU/I2PMS/AMF)')),
                ('Previous_Opening_Diesel_stock_Before_Filling', models.TextField(null=True, verbose_name='Previous Opening Diesel stock Before Filling')),
                ('Current_Opening_Diesel_stock_Before_Filling', models.TextField(null=True, verbose_name='Current Opening Diesel stock Before Filling')),
                ('Previous_Filled_Ltrs', models.TextField(null=True, verbose_name='Previous Filled Ltrs')),
                ('Current_Filled_Ltrs', models.TextField(null=True, verbose_name='Current Filled Ltrs')),
                ('Previous_Diesel_Bill_Number', models.TextField(null=True, verbose_name='Previous Diesel Bill Number')),
                ('Current_Diesel_Bill_Number', models.TextField(null=True, verbose_name='Current Diesel Bill Number')),
                ('Previous_Remarks_If_any', models.TextField(null=True, verbose_name='Previous Remarks If any')),
                ('Current_Remarks_If_any', models.TextField(null=True, verbose_name='Current Remarks If any')),
                ('No_of_days_since_previous_filling', models.TextField(null=True, verbose_name='No of days since previous filling')),
                ('Calculated_CPH_HMR', models.TextField(null=True, verbose_name='Calculated CPH (HMR)')),
                ('Calculated_CPH_As_per_PIU_I2PMS_AMF', models.TextField(null=True, verbose_name='Calculated CPH (As per PIU/I2PMS/AMF)')),
                ('Calculated_DG_HR_HMR', models.TextField(null=True, verbose_name='Calculated DG HR (HMR)')),
                ('Calculated_DG_HR_As_per_PIU_I2PMS_AMF', models.TextField(null=True, verbose_name='Calculated DG HR (As per PIU/I2PMS/AMF)')),
                ('Calculated_EB_KWH_As_per_Meter', models.TextField(null=True, verbose_name='Calculated EB KWH (As per Meter)')),
                ('Calculated_EB_HR_As_per_PIU_I2PMS_AMF', models.TextField(null=True, verbose_name='Calculated EB HR (As per PIU/I2PMS/AMF)')),
                ('Deviation', models.TextField(null=True, verbose_name='Deviation')),
                ('Global_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sitefixed')),
            ],
        ),
    ]
