# Generated by Django 5.0.6 on 2024-07-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_premonsoonimages_pmcl'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='circle',
            field=models.CharField(choices=[('All', 'All'), ('JK', 'JK'), ('UPE', 'UPE'), ('UPW', 'UPW'), ('HP', 'HP'), ('HR', 'HR'), ('PB', 'PB'), ('DL', 'DL'), ('MU', 'MU'), ('MH', 'MH'), ('GJ', 'GJ'), ('RJ', 'RJ'), ('RJ', 'RJ'), ('CG', 'CG'), ('AS', 'AS'), ('NE', 'NE'), ('WB', 'WB'), ('KOL', 'KOL'), ('OD', 'OD'), ('JH', 'JH'), ('BH', 'BH'), ('AP', 'AP'), ('TS', 'TS'), ('TN', 'TN'), ('KN', 'KN'), ('KL', 'KL')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='region',
            field=models.CharField(choices=[('All', 'All'), ('East', 'East'), ('West', 'West'), ('North', 'North'), ('South', 'South')], max_length=30, null=True),
        ),
    ]
