# Generated by Django 5.0 on 2024-07-05 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_users_circle_users_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsOfRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(null=True, upload_to='Documents_repository/%y', verbose_name='Files')),
                ('file_name', models.TextField(null=True, verbose_name='File Name')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.TextField(null=True, unique=True, verbose_name='Document ID')),
                ('project_type', models.CharField(choices=[('Fuel Pump Automation Work', 'Feul Pump Automation Work'), ('DG R&R, For ATC, Ascend, TVI', 'DG R&R, For ATC, Ascend, TVI'), ('EV Charger I&C, PM & BDN Calls', 'EV Charger I&C, PM & BDN Calls'), ('Retail DG Repair', 'Retail DG Repair'), ('5G Upgradation For ATC', '5G Upgradation For ATC'), ('FTTH For Microscan', 'FTTH For Microscan')], max_length=100, null=True, verbose_name='Project Types')),
                ('region', models.CharField(choices=[('East', 'East'), ('West', 'West'), ('North', 'North'), ('South', 'South')], max_length=100, null=True, verbose_name='Regions')),
                ('site_docs_id', models.CharField(max_length=100, null=True, verbose_name='SiteID & DocumentID')),
                ('circles', models.CharField(choices=[('JK', 'JK'), ('UPE', 'UPE'), ('UPW', 'UPW'), ('HP', 'HP'), ('HR', 'HR'), ('PB', 'PB'), ('DL', 'DL'), ('MU', 'MU'), ('MH', 'MH'), ('GJ', 'GJ'), ('RJ', 'RJ'), ('RJ', 'RJ'), ('CG', 'CG'), ('AS', 'AS'), ('NE', 'NE'), ('WB', 'WB'), ('KOL', 'KOL'), ('OD', 'OD'), ('JH', 'JH'), ('BH', 'BH'), ('AP', 'AP'), ('TS', 'TS'), ('TN', 'TN'), ('KN', 'KN'), ('KL', 'KL')], max_length=50, verbose_name='Circles')),
                ('file_category', models.CharField(choices=[('FSR', 'FSR'), ('Eng', 'Eng'), ('Alt', 'Alt'), ('Site', 'Site'), ('JMS', 'JMS'), ('WCC', 'WCC')], null=True, verbose_name='File Category')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(related_name='Documents', to='app.documentsofrepository')),
            ],
        ),
    ]
