# Generated by Django 5.0 on 2024-07-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_documentsofrepository_documentrepository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrepository',
            name='file_category',
            field=models.CharField(choices=[('FSR', 'FSR'), ('Civil Image', 'Civil Image'), ('Civil Work', 'Civil Work'), ('Electrical Work', 'Electrical Work'), ('Site Image', 'Site Image')], null=True, verbose_name='File Category'),
        ),
    ]
