# Generated by Django 5.0 on 2024-07-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_documentrepository_file_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrepository',
            name='circles',
            field=models.CharField(choices=[('JK', 'JK'), ('UPE', 'UPE'), ('UPW', 'UPW'), ('HP', 'HP'), ('HR', 'HR'), ('PB', 'PB'), ('DL', 'DL'), ('MU', 'MU'), ('MH', 'MH'), ('GJ', 'GJ'), ('RJ', 'RJ'), ('MP', 'MP'), ('CG', 'CG'), ('AS / NE', 'AS / NE'), ('WB / KOL', 'WB / KOL'), ('OD', 'OD'), ('JH', 'JH'), ('BH', 'BH'), ('AP', 'AP'), ('TS', 'TS'), ('TN', 'TN'), ('KN', 'KN'), ('KL', 'KL')], max_length=50, verbose_name='Circles'),
        ),
        migrations.AlterField(
            model_name='documentrepository',
            name='file_category',
            field=models.CharField(choices=[('FSR', 'FSR'), ('Civil Image', 'Civil Image'), ('Civil Work', 'Civil Work'), ('Electrical Work', 'Electrical Work'), ('Site Image', 'Site Image'), ('PM Image', 'PM Image')], null=True, verbose_name='File Category'),
        ),
        migrations.AlterField(
            model_name='users',
            name='circle',
            field=models.CharField(choices=[('All', 'All'), ('JK', 'JK'), ('UPE', 'UPE'), ('UPW', 'UPW'), ('HP', 'HP'), ('HR', 'HR'), ('PB', 'PB'), ('DL', 'DL'), ('MU', 'MU'), ('MH', 'MH'), ('GJ', 'GJ'), ('RJ', 'RJ'), ('MP', 'MP'), ('CG', 'CG'), ('AS / NE', 'AS / NE'), ('WB / KOL', 'WB / KOL'), ('OD', 'OD'), ('JH', 'JH'), ('BH', 'BH'), ('AP', 'AP'), ('TS', 'TS'), ('TN', 'TN'), ('KN', 'KN'), ('KL', 'KL')], max_length=10, null=True),
        ),
    ]
