# Generated by Django 5.0 on 2024-07-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_users_date_joined_alter_users_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('ASM', 'ASM'), ('RSM', 'RSM')], max_length=50, null=True),
        ),
    ]
