# Generated by Django 5.0 on 2024-07-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_users_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
