# Generated by Django 5.0 on 2024-07-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_projecttypemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customers', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
