# Generated by Django 5.0.6 on 2024-07-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_customerdatamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('ASM', 'ASM'), ('RSM', 'RSM'), ('Assistant Manager', 'Assistant Manager'), ('Manager', 'Manager'), ('General Manager', 'General Manager'), ('Deputy Manager', 'Deputy Manager'), ('CEO', 'CEO'), ('CFO', 'CFO'), ('Service Head', 'Service Head'), ('Engineer', 'Engineer'), ('Senior Engineer', 'Senior Engineer'), ('IT Executive', 'IT Executive'), ('CAD Executive', 'CAD Executive'), ('Technician', 'Technician'), ('Sales', 'Sales')], max_length=50, null=True),
        ),
    ]
