# Generated by Django 5.0.6 on 2024-07-19 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_users_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsMasterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=250, null=True)),
                ('site_name', models.CharField(max_length=250, null=True)),
                ('customer', models.CharField(max_length=250, null=True)),
                ('project_type', models.CharField(max_length=250, null=True)),
                ('customer_expected_target_date', models.DateField(null=True)),
                ('assigned_to_asm', models.CharField(max_length=250, null=True)),
                ('sales_remark', models.TextField(null=True)),
                ('project_description', models.TextField(null=True)),
                ('assigned_to_technician', models.CharField(max_length=250, null=True)),
                ('technician_target_date', models.DateField(null=True)),
                ('asm_remarks', models.TextField(null=True)),
                ('project_status', models.CharField(max_length=250, null=True)),
                ('completed_date', models.DateField(null=True)),
                ('technician_remarks', models.TextField(null=True)),
                ('pendings', models.CharField(max_length=50, null=True)),
                ('completed', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
