# Generated by Django 5.0 on 2024-08-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_projectsmastermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrepository',
            name='file_category',
            field=models.CharField(choices=[('FSR', 'FSR'), ('Civil Image', 'Civil Image'), ('Civil Work', 'Civil Work'), ('Electrical Work', 'Electrical Work'), ('Site Image', 'Site Image'), ('PM Image', 'PM Image'), ('Survey Report', 'Survey Report'), ('I&C Report ', 'I&C Report ')], null=True, verbose_name='File Category'),
        ),
        migrations.AlterField(
            model_name='users',
            name='circle',
            field=models.CharField(choices=[('None', 'None'), ('All', 'All'), ('JK', 'JK'), ('UPE', 'UPE'), ('UPW', 'UPW'), ('HP', 'HP'), ('HR', 'HR'), ('PB', 'PB'), ('DL', 'DL'), ('MU', 'MU'), ('MH', 'MH'), ('GJ', 'GJ'), ('RJ', 'RJ'), ('MP', 'MP'), ('CG', 'CG'), ('AS / NE', 'AS / NE'), ('WB / KOL', 'WB / KOL'), ('OD', 'OD'), ('JH', 'JH'), ('BH', 'BH'), ('AP', 'AP'), ('TS', 'TS'), ('TN', 'TN'), ('KN', 'KN'), ('KL', 'KL')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='department',
            field=models.CharField(choices=[('None', 'None'), ('HR', 'HR'), ('IT', 'IT'), ('Accounts', 'Accounts'), ('CAD', 'CAD'), ('SCM', 'SCM'), ('Technical', 'Technical'), ('Sales', 'Sales')], max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='region',
            field=models.CharField(choices=[('None', 'None'), ('All', 'All'), ('East', 'East'), ('West', 'West'), ('North', 'North'), ('South', 'South')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('None', 'None'), ('ASM', 'ASM'), ('RSM', 'RSM'), ('Assistant Manager', 'Assistant Manager'), ('Manager', 'Manager'), ('General Manager', 'General Manager'), ('Deputy Manager', 'Deputy Manager'), ('Deputy General Manager', 'Deputy General Manager'), ('CEO', 'CEO'), ('Senior Vice President', 'Senior Vice President'), ('Service Head', 'Service Head'), ('Engineer', 'Engineer'), ('Senior Engineer', 'Senior Engineer'), ('IT Executive', 'IT Executive'), ('CAD Executive', 'CAD Executive'), ('Technician', 'Technician'), ('Sales', 'Sales'), ('Vice President', 'Vice President'), ('Associate Vice President', 'Associate Vice President'), ('MIS Executive', 'MIS Executive')], max_length=50, null=True),
        ),
    ]
